[build]
  command = "npm run build"
  publish = "dist"
[dev]
  command = "npm run dev"
  publish = "dist"
[build.environment]
  NODE_ENV = "production"
[context.production.environment]
  SERVER_PORT = "80"
[context.deploy-preview.environment]
  SERVER_PORT = "3000"