[build]
  command = "npm run build" # Replace with your build command
  functions = "functions"  # The directory where your serverless functions reside

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200