[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "lts/*"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/:splat"
  status = 200
  force = true